---
apiVersion: v1
kind: Namespace
metadata:
  name: satellite
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: satellite
  name: catalog-deploy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: catalog-app
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: catalog-app
    spec:
      containers:
      - image: erangi123/satellite:main
        imagePullPolicy: Always
        name: catalog-app
        ports:
        - containerPort: 8089
---
apiVersion: v1
kind: Service
metadata:
  namespace: satellite
  name: catalog-service
spec:
  ports:
    - port: 8089
      targetPort: 8089
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: catalog-app
  type: LoadBalancer
status:
  loadBalancer: {}




          
