---
apiVersion: v1
kind: Namespace
metadata:
  name: satellite
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: satellite
  name: monitoring-deploy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: monitoring-app
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: monitoring-app
    spec:
      containers:
      - image: erangi123/satellite:main
        imagePullPolicy: Always
        name: monitoring-app
        ports:
        - containerPort: 8089
---
apiVersion: v1
kind: Service
metadata:
  namespace: satellite
  name: monitoring-service
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8089
    targetPort: 8089
  selector:
    app.kubernetes.io/name: monitoring-app