apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-k8s-deployment
  labels:
    app: docker-k8s
spec:
  replicas: 3
  selector:
    matchLabels:
      app: docker-k8s
  template:
    metadata:
      labels:
        app: docker-k8s
    spec:
      containers:
      - name: docker-k8s
        image: erangi123/satellite:main
        ports:
          - containerPort: 8089